In [1]:
import numpy as np
import torch

In [7]:
a = torch.zeros((10, 20))
a.shape[0]

10

In [9]:
a = torch.tensor([1])
b = torch.tensor([2])
c = torch.tensor([3])
d = torch.tensor([1, 2, 3, 4])
torch.min(torch.tensor([b, a, c]), dim=-1)

torch.return_types.min(
values=tensor(1),
indices=tensor(1))

In [14]:
a = [torch.tensor([1]), torch.tensor([2]), torch.tensor([-1])]
torch.min(torch.tensor(a))

tensor(-1)

In [3]:
import torch
a = torch.randn((3, 4))
print(a)
torch.min(a, dim=-1).values

tensor([[-0.6406, -0.0507, -0.8493,  1.4193],
        [ 2.1156, -1.4731, -0.9748, -0.3582],
        [-0.6984, -0.1254, -0.2298, -0.6399]])


tensor([-0.8493, -1.4731, -0.6984])

In [11]:
z = torch.rand((2, 3, 4))
x = z * (torch.ones((3, 4)) * 0.5)
z, x

(tensor([[[0.6193, 0.0415, 0.9194, 0.1198],
          [0.5799, 0.3113, 0.0211, 0.7621],
          [0.5014, 0.8039, 0.2148, 0.5552]],
 
         [[0.5760, 0.4805, 0.5986, 0.8158],
          [0.3601, 0.3482, 0.2324, 0.0215],
          [0.9907, 0.5854, 0.6088, 0.3497]]]),
 tensor([[[0.3096, 0.0208, 0.4597, 0.0599],
          [0.2899, 0.1557, 0.0106, 0.3811],
          [0.2507, 0.4019, 0.1074, 0.2776]],
 
         [[0.2880, 0.2403, 0.2993, 0.4079],
          [0.1800, 0.1741, 0.1162, 0.0107],
          [0.4953, 0.2927, 0.3044, 0.1749]]]))

In [7]:
torch.tensor(0.0).item()

0.0

In [5]:
from torch import nn

p = nn.Parameter(torch.zeros((3, 5)))

NameError: name 'torch' is not defined

In [19]:
y = torch.rand((3, 5))

In [1]:
from comblearn.nn import Universe

u = Universe(8, range(50), 0.2)
u.U

Parameter containing:
tensor([[0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
         1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1.],
        [0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
         0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0.,
         0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0.,
         1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1

In [3]:
import torch

u(torch.tensor([[0, 1, 0, 0, 1, 0, 0, 1], [1, 0, 0, 0, 1, 1, 0, 0]]).float())

tensor([24, 33])

In [27]:
torch.reshape(torch.arange(48), (-1, 6))[torch.tensor([1 ,2 , 5])]

tensor([[ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [30, 31, 32, 33, 34, 35]])

In [24]:
p.data = y
p

Parameter containing:
tensor([[0.0358, 0.6200, 0.8616, 0.5158, 0.3462],
        [0.2916, 0.9084, 0.2513, 0.0133, 0.4370],
        [0.4169, 0.0154, 0.3750, 0.8792, 0.5678]], requires_grad=True)

In [58]:
def projection_simplex_sort_2d(v, z=1):
        """v array of shape (n_features, n_samples)."""
        p, n = v.shape
        u = torch.sort(v, dim=0, descending=True)[0]
        pi = torch.cumsum(u, dim=0) - z
        ind = torch.reshape(torch.arange(p) + 1, (-1, 1))
        mask = (u - pi / ind) > 0
        rho = p - 1 - torch.argmax(mask.flip([0]).int(), dim=0)
        theta = pi[tuple([rho, torch.arange(n)])] / (rho + 1)
        w = torch.maximum(v - theta, torch.tensor(0))

        return w

In [65]:
torch.rand((3, 5), requires_grad=True).requires_grad

True

In [59]:
projection_simplex_sort_2d(torch.reshape(torch.rand((30)), (-1, 5)))

tensor([[0.6195, 0.0127, 0.2110, 0.2128, 0.2532],
        [0.1892, 0.2517, 0.5508, 0.8727, 0.9937],
        [0.0597, 0.8180, 0.9768, 0.0866, 0.7386],
        [0.3962, 0.9267, 0.7149, 0.6143, 0.6210],
        [0.6713, 0.2451, 0.3003, 0.5584, 0.8330],
        [0.1222, 0.6765, 0.9231, 0.2087, 0.7415]])
tensor([[0.6713, 0.9267, 0.9768, 0.8727, 0.9937],
        [0.6195, 0.8180, 0.9231, 0.6143, 0.8330],
        [0.3962, 0.6765, 0.7149, 0.5584, 0.7415],
        [0.1892, 0.2517, 0.5508, 0.2128, 0.7386],
        [0.1222, 0.2451, 0.3003, 0.2087, 0.6210],
        [0.0597, 0.0127, 0.2110, 0.0866, 0.2532]])
tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [0, 0, 1, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0]], dtype=torch.int32)


tensor([[0.3905, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0094, 0.5242, 0.4081],
        [0.0000, 0.3442, 0.4354, 0.0000, 0.1530],
        [0.1672, 0.4530, 0.1735, 0.2658, 0.0355],
        [0.4423, 0.0000, 0.0000, 0.2100, 0.2474],
        [0.0000, 0.2028, 0.3817, 0.0000, 0.1560]])

In [41]:
def projection_simplex(v, z=1):
        """v array of shape (n_features, n_samples)."""
        p, n = v.shape
        print('V:', v)
        u = np.sort(v, axis=0)[::-1, ...]
        print('U:', u)
        pi = np.cumsum(u, axis=0) - z
        ind = (np.arange(p) + 1).reshape(-1, 1)
        mask = (u - pi / ind) > 0
        print('M:', mask)
        print('X:', mask[::-1, ...])
        rho = p - 1 - np.argmax(mask[::-1, ...], axis=0)
        theta = pi[tuple([rho, np.arange(n)])] / (rho + 1)
        w = np.maximum(v - theta, 0)

        return w

In [3]:
x = torch.rand((3, 5)).to('cuda')
x

tensor([[0.4562, 0.1276, 0.3137, 0.7058, 0.5711],
        [0.7508, 0.6672, 0.4414, 0.1301, 0.8136],
        [0.6931, 0.3540, 0.8496, 0.6317, 0.8545]], device='cuda:0')

In [5]:
(x + 0.2 > 0.5)

tensor([[ True, False,  True,  True,  True],
        [ True,  True,  True, False,  True],
        [ True,  True,  True,  True,  True]], device='cuda:0')

In [60]:
arr = np.array([[0.6195, 0.0127, 0.2110, 0.2128, 0.2532],
        [0.1892, 0.2517, 0.5508, 0.8727, 0.9937],
        [0.0597, 0.8180, 0.9768, 0.0866, 0.7386],
        [0.3962, 0.9267, 0.7149, 0.6143, 0.6210],
        [0.6713, 0.2451, 0.3003, 0.5584, 0.8330],
        [0.1222, 0.6765, 0.9231, 0.2087, 0.7415]])

# projection_simplex(np.reshape(np.random.rand((30)), (-1, 5)))
projection_simplex(arr)

V: [[0.6195 0.0127 0.211  0.2128 0.2532]
 [0.1892 0.2517 0.5508 0.8727 0.9937]
 [0.0597 0.818  0.9768 0.0866 0.7386]
 [0.3962 0.9267 0.7149 0.6143 0.621 ]
 [0.6713 0.2451 0.3003 0.5584 0.833 ]
 [0.1222 0.6765 0.9231 0.2087 0.7415]]
U: [[0.6713 0.9267 0.9768 0.8727 0.9937]
 [0.6195 0.818  0.9231 0.6143 0.833 ]
 [0.3962 0.6765 0.7149 0.5584 0.7415]
 [0.1892 0.2517 0.5508 0.2128 0.7386]
 [0.1222 0.2451 0.3003 0.2087 0.621 ]
 [0.0597 0.0127 0.211  0.0866 0.2532]]
M: [[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [False False  True False  True]
 [False False False False  True]
 [False False False False False]]
X: [[False False False False False]
 [False False False False  True]
 [False False  True False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


array([[0.3905    , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.0094    , 0.52423333, 0.40814   ],
       [0.        , 0.34426667, 0.4354    , 0.        , 0.15304   ],
       [0.1672    , 0.45296667, 0.1735    , 0.26583333, 0.03544   ],
       [0.4423    , 0.        , 0.        , 0.20993333, 0.24744   ],
       [0.        , 0.20276667, 0.3817    , 0.        , 0.15594   ]])

In [28]:
projection_simplex(np.ones((3, 5)))

V: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
U: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333]])

In [22]:
x = torch.tensor([2, 3], device='cuda')

In [23]:
y = x.cpu().numpy()

In [24]:
z = torch.from_numpy(y)

In [27]:
z = z.to('cuda:0')

In [28]:
z

tensor([2, 3], device='cuda:0')

In [12]:
x.device

device(type='cuda', index=0)

In [11]:
y = x.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [69]:
b = torch.zeros(3,3)

In [70]:
b.requires_grad = True

In [71]:
c = b+5

In [72]:
c

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]], grad_fn=<AddBackward0>)

In [73]:
d = torch.sum(c[:,2])

In [74]:
d

tensor(15., grad_fn=<SumBackward0>)

In [75]:
d.backward()

In [76]:
b.grad

tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.]])

In [79]:
b.grad.value()

AttributeError: 'Tensor' object has no attribute 'value'

In [68]:
m

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [67]:
b.grad.zero_()

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [56]:
b.grad

tensor([0.])

In [47]:
def projection_simplex_sort_2d(v, z=1):
    """v array of shape (n_features, n_samples)."""
    p, n = v.shape
    u = np.sort(v, axis=0)[::-1, ...]
    pi = np.cumsum(u, axis=0) - z
    ind = (np.arange(p) + 1).reshape(-1, 1)
    mask = (u - pi / ind) > 0
    rho = p - 1 - np.argmax(mask[::-1, ...], axis=0)
    theta = pi[tuple([rho, np.arange(n)])] / (rho + 1)
    w = np.maximum(v - theta, 0)
    return w

In [50]:
temp = np.zeros((8, 3))
temp = projection_simplex_sort_2d(temp.T).T
temp

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])

In [43]:
v = np.zeros((2, 3))
projection_simplex_sort_2d(v)

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

In [2]:
a = {1: 2, 3: 4}
for k, v in a.items():
    print(k, v)

1 2
3 4


In [3]:
import numpy as np

In [22]:
a = np.ones((3, 3))

In [23]:
l = [0, 2]

In [24]:
a[l, :]

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
a[:, 2] = 0
a

array([[1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.]])

In [6]:
import torch

In [17]:
output = torch.multinomial(torch.tensor([0.25, 0.5, 0.25]), 1)
z = [(output == i).float() for i in range(5)]

In [19]:
output = torch.multinomial(torch.tensor([0.25, 0.5, 0.25]), 1)

In [21]:
output.item()

1

In [25]:
a = [4, 2, 5]
a.sort()

In [26]:
a

[2, 4, 5]

In [28]:
def check(a):
    a.append('test')

a = [1, 2]
check(a)
print(a)

[1, 2, 'test']


In [33]:
a = {}
if a == False:
    print('hello')

In [34]:
a.items()

dict_items([])

In [35]:
len(a.items())

0

In [36]:
len(a)

0

In [37]:
a = {1: 2}
print(len(a))

1


In [38]:
list(range(3))

[0, 1, 2]

In [39]:
a = [4, 3, 1]

In [41]:
a.remove(1)
a

ValueError: list.remove(x): x not in list

In [5]:
import random

In [9]:
a = set(random.sample(range(100), 4))

In [11]:
a.intersection({2, 88})

{88}