In [21]:
import numpy as np
import torch

In [22]:
x = torch.tensor([2, 3], device='cuda')

In [23]:
y = x.cpu().numpy()

In [24]:
z = torch.from_numpy(y)

In [27]:
z = z.to('cuda:0')

In [28]:
z

tensor([2, 3], device='cuda:0')

In [12]:
x.device

device(type='cuda', index=0)

In [11]:
y = x.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [69]:
b = torch.zeros(3,3)

In [70]:
b.requires_grad = True

In [71]:
c = b+5

In [72]:
c

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]], grad_fn=<AddBackward0>)

In [73]:
d = torch.sum(c[:,2])

In [74]:
d

tensor(15., grad_fn=<SumBackward0>)

In [75]:
d.backward()

In [76]:
b.grad

tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.]])

In [79]:
b.grad.value()

AttributeError: 'Tensor' object has no attribute 'value'

In [68]:
m

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [67]:
b.grad.zero_()

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [56]:
b.grad

tensor([0.])

In [47]:
def projection_simplex_sort_2d(v, z=1):
    """v array of shape (n_features, n_samples)."""
    p, n = v.shape
    u = np.sort(v, axis=0)[::-1, ...]
    pi = np.cumsum(u, axis=0) - z
    ind = (np.arange(p) + 1).reshape(-1, 1)
    mask = (u - pi / ind) > 0
    rho = p - 1 - np.argmax(mask[::-1, ...], axis=0)
    theta = pi[tuple([rho, np.arange(n)])] / (rho + 1)
    w = np.maximum(v - theta, 0)
    return w

In [50]:
temp = np.zeros((8, 3))
temp = projection_simplex_sort_2d(temp.T).T
temp

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])

In [43]:
v = np.zeros((2, 3))
projection_simplex_sort_2d(v)

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

In [2]:
a = {1: 2, 3: 4}
for k, v in a.items():
    print(k, v)

1 2
3 4


In [3]:
import numpy as np

In [22]:
a = np.ones((3, 3))

In [23]:
l = [0, 2]

In [24]:
a[l, :]

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
a[:, 2] = 0
a

array([[1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.]])

In [6]:
import torch

In [17]:
output = torch.multinomial(torch.tensor([0.25, 0.5, 0.25]), 1)
z = [(output == i).float() for i in range(5)]

In [19]:
output = torch.multinomial(torch.tensor([0.25, 0.5, 0.25]), 1)

In [21]:
output.item()

1

In [25]:
a = [4, 2, 5]
a.sort()

In [26]:
a

[2, 4, 5]

In [28]:
def check(a):
    a.append('test')

a = [1, 2]
check(a)
print(a)

[1, 2, 'test']


In [33]:
a = {}
if a == False:
    print('hello')

In [34]:
a.items()

dict_items([])

In [35]:
len(a.items())

0

In [36]:
len(a)

0

In [37]:
a = {1: 2}
print(len(a))

1


In [38]:
list(range(3))

[0, 1, 2]

In [39]:
a = [4, 3, 1]

In [41]:
a.remove(1)
a

ValueError: list.remove(x): x not in list

In [5]:
import random

In [9]:
a = set(random.sample(range(100), 4))

In [11]:
a.intersection({2, 88})

{88}